Add support for multiple account owners in Unit
trysandbar/sandbar-js pull request #31
Opened 2022-08-04 21:12 UTC by rahul-x-verma

2022-08-04 21:14 UTC, rahul-x-verma commented on packages/sandbar/src/client.ts
> +  convertUnitRelationships<T> (unitObject: CorrectUnitRelationships<T>) : any | undefined {
Is there a better return type than "any"? I tried "T", but that didn't compile.

2022-08-04 21:16 UTC, rahul-x-verma commented
Verified locally by modifying the unit-example library to use the new endpoints.

2022-08-04 21:25 UTC, ryanrhee commented on packages/sandbar/src/client.ts
> +  convertUnitRelationships<T> (unitObject: CorrectUnitRelationships<T>) : any | undefined {
definitely a better type. please provide more details on how / why using `T` did not compile.

2022-08-04 21:26 UTC, ryanrhee requested changes
also, jest is failing

2022-08-04 22:42 UTC, ryanrhee commented on packages/sandbar/src/client.ts
> +  convertUnitRelationships<T>(
move this out of the class

2022-08-05 16:48 UTC, ryanrhee approved these changes

2022-08-05 17:18 UTC, merged